# Generated by Django 2.2.9 on 2020-02-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_customer_user', to='shop.MyUser'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=132119309800178, editable=False),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_customer_user', to='shop.MyUser'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='uuid',
            field=models.UUIDField(default=13247239997289, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer_user', to='shop.MyUser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=76641412162994, editable=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='uuid',
            field=models.UUIDField(default=131055446178350, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seller_user', to='shop.MyUser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=131544589418048, editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_customer_user', to='shop.MyUser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=136077585918882, editable=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='seller_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_seller_user', to='shop.MyUser'),
        ),
    ]
