# Generated by Django 2.2.9 on 2020-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200225_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Seller'), ('C', 'Customer')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='uuid',
            field=models.UUIDField(default=128912246782136, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=13104616013491, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=17965480851081, editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=110257397770970, editable=False),
        ),
    ]
