# Generated by Django 2.2.9 on 2020-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200219_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=78774760995677, editable=False),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='uuid',
            field=models.UUIDField(default=126654907391751, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=48513055955455, editable=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='uuid',
            field=models.UUIDField(default=69541121900972, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=92933078457178, editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=39501530341436, editable=False),
        ),
    ]
