# Generated by Django 2.2.9 on 2020-02-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200219_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_customer_user', to='shop.MyUser'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=31572330115793, editable=False),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='uuid',
            field=models.UUIDField(default=130323002381223, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=86731537152249, editable=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='uuid',
            field=models.UUIDField(default=96484281496794, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=65248890376560, editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=126931417838262, editable=False),
        ),
    ]
