# Generated by Django 2.2.9 on 2020-02-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200220_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='uuid',
            field=models.UUIDField(default=95833835274931, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=53552005933974, editable=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='uuid',
            field=models.UUIDField(default=50371349299723, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=103789431536419, editable=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=91450470760264, editable=False),
        ),
    ]
