# Generated by Django 2.2.9 on 2020-03-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200312_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='uuid',
        ),
    ]
