# Generated by Django 2.2.9 on 2020-03-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200312_0549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
